// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVWRwihwWOlXh_wKw3ckHa6qJVYhbyADI',
    appId: '1:60561356113:web:8580e9ed9fadf116350f70',
    messagingSenderId: '60561356113',
    projectId: 'loginscreen-2f1f8',
    authDomain: 'loginscreen-2f1f8.firebaseapp.com',
    storageBucket: 'loginscreen-2f1f8.firebasestorage.app',
    measurementId: 'G-YM5BVCPJND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQMHV2InwgwbQZq6spmOBnozPhFNwXDcw',
    appId: '1:60561356113:android:1c0e9e4f5e8ede22350f70',
    messagingSenderId: '60561356113',
    projectId: 'loginscreen-2f1f8',
    storageBucket: 'loginscreen-2f1f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9j8mu6Y1q89ruloOgGsrtzvRoLav2XSA',
    appId: '1:60561356113:ios:eda7e103dc4d95b1350f70',
    messagingSenderId: '60561356113',
    projectId: 'loginscreen-2f1f8',
    storageBucket: 'loginscreen-2f1f8.firebasestorage.app',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9j8mu6Y1q89ruloOgGsrtzvRoLav2XSA',
    appId: '1:60561356113:ios:eda7e103dc4d95b1350f70',
    messagingSenderId: '60561356113',
    projectId: 'loginscreen-2f1f8',
    storageBucket: 'loginscreen-2f1f8.firebasestorage.app',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVWRwihwWOlXh_wKw3ckHa6qJVYhbyADI',
    appId: '1:60561356113:web:75dd8a4a03844ce9350f70',
    messagingSenderId: '60561356113',
    projectId: 'loginscreen-2f1f8',
    authDomain: 'loginscreen-2f1f8.firebaseapp.com',
    storageBucket: 'loginscreen-2f1f8.firebasestorage.app',
    measurementId: 'G-YK94BRLBRT',
  );

}